openapi: '3.0.2'
info:
  title: Servers demo API
  version: '1.0'
  description: Test API for testing AMF service
  termsOfService: http://example.com/terms/
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: https://development.gigantic-server.com/v1
    description: Development server
  - url: https://staging.gigantic-server.com/v1
    description: Staging server
  - url: https://api.gigantic-server.com/v1
    description: Production server
  - url: https://{username}.gigantic-server.com:{port}/{basePath}
    description: The production API server
    variables:
      username:
        default: demo
        description: this value is assigned by the service provider, in this example `gigantic-server.com`
      port:
        enum:
          - '8443'
          - '443'
        default: '8443'
        example: '443'
      basePath:
        default: v2

externalDocs:
  description: ABout this API.
  url: https://domain.com

components:
  schemas:
    GeneralError:
      type: object
      properties:
        code:
          type: integer
          format: int32
          examples:
            minimum:
              value: 200
              summary: The minimal code value
            maximum:
              value: 599
              summary: The highest code value.
        message:
          type: string
    Category:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    Tag:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    Article:
      description: Representation of an article with title and body in CommonMark format.
      type: object
      properties:
        id:
          type: string
          description: The unique ID of this article, generated by the API implementation upon creation of the article.
          readOnly: true
        title:
          description: The title of the article, in CommonMark format.
          type: string
          minLength: 3
      externalDocs:
        description: Find more about this type
        url: https://api.com
      example:
        id: "e1h2b3egvg46df5"
        title: "My new article"
  parameters:
    skipParam:
      name: skip
      in: query
      description: number of items to skip
      required: true
      schema:
        type: integer
        format: int32
    limitParam:
      name: limit
      in: query
      description: max records to return
      required: true
      schema:
        type: integer
        format: int32
  responses:
    NotFound:
      description: Entity not found.
    IllegalInput:
      description: Illegal input for operation.
    GeneralError:
      description: General Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GeneralError'
          example:
            code: 400
            message: "Client error"
            summary: A client request error
  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: header
    petstore_auth:
      type: oauth2
      flows: 
        implicit:
          authorizationUrl: http://example.org/api/oauth/dialog
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets

paths:
  /pets:
    get:
      description: Returns all pets from the system that the user has access to
      summary: Find all pets
      operationId: listPets
      tags:
        - pet
      security:
        - petstore_auth:
          - write:pets
          - read:pets
      responses:
        '200':
          description: A list of pets.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
                example:
                  - id: 1
                    name: Category 1
                  - id: 2
                    name: Category 2

  /default:
    description: A default path to the API
    get:
      summary: "A get method"
      responses:
        '200':
          description: Successful response
    post:
      summary: Add something
      requestBody:
        content:  # Response body
          application/json:  # Media type
            schema:
              $ref: "#/components/schemas/Article"
      responses:
        '201':
          description: Successful creation
          content:
            appliication/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/Article"
                  - type: object
                    properties:
                      description:
                        type: string
              examples:
                Dinosaurs in the space:
                  value:
                    id: b2eb7b82-ad0f-11eb-8529-0242ac130003
                    title: Dinosaurs in the space
                  summary: A book about dinosaurs
                Living on a prayer:
                  value:
                    id: b2eb7dc6-ad0f-11eb-8529-0242ac130003
                    name: Living on a prayer
                  summary: A book about praying
            application/xml:
              schema:
                $ref: '#/components/schemas/Article'
              examples:
                xml:
                  summary: A sample XML response
                  value: '<objects><object><id>1</id><name>new</name></object><object><id>2</id></object></objects>'
            text/html:
              schema:
                type: string
              examples:
                html:
                  summary: A list containing two items
                  value: '<html><body><ul><li>item 1</li><li>item 2</li></ul></body></html>'
